### PR TITLE
fix algorithm error of ADKIsLongerScreen (the shorter ratio of screen width / height, the longer screen)

### PR DESCRIPTION
**Pull request by BramYeh**
the shorter ratio of screen width / height, the longer screen

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by anistarsung** [comment]
Short screen means width / height should bigger than long screen's. For example: iPad is short screen device and iPhone 6 is long screen device.

**Comment by kenobilyh** [comment]
Good idea for mock fixedCoordinateSpace!

**Comment by kenobilyh** [comment]
👍

**Pull request merged**
