### PR TITLE
call UIGraphicsEndImageContext() again to release all image contexts …

### PR DESCRIPTION
**Pull request by cdsurfer0212**
…opened by the message

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kenobilyh** [comment]
Good work! This PR solve coordinate incorrect after call ADKGaussianBlurWithRadius.

**Comment by kenobilyh** [comment]
👍

**Pull request merged**
