### PR TITLE
Improve documentation [skip ci]

### PR DESCRIPTION
**Pull request by lihengl**
Hi, I've noticed some issues while reading through the project description. This should clear it out a bit!

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kenobilyh** [comment]
Thanks for fix so soon. Please let us review it tomorrow.👏

**Comment by kenobilyh** [comment]
👍

**Pull request merged**
